package com.aura.admin.adminqamm.util;

public enum PermitionENUM {
    SUDO(0),
    ADMINISTRADOR_DE_ROLES(1),
    ADMINISTRADOR_DE_ROLES_VER(2),
    USUARIOS_ADMINISTRADOR(3),
    USUARIOS_VER(4),
    USUARIOS_CREAR(5),
    USUARIOS_MODIFICAR(6),
    USUARIOS_BORRAR(7),
    USUARIOS_SEGURIDAD_ADMINISTRADOR(8),
    USUARIOS_SEGURIDAD_VER(9),
    USUARIOS_CLIENTE_ADMINISTRADOR(10),
    USUARIOS_CLIENTE_VER(11),
    INTERFACES_ADMINISTRADOR(12),
    INTERFACES_VER(13),
    SERVICIOS_ADMINISTRADOR(14),
    SERVICIOS_VER(15),
    SERVICIOS_CATALOGOS_ADMINISTRADOR(16),
    SERVICIOS_CATALOGOS_VER(17),
    PROMOCIONES_ADMINISTRADOR(18),
    PROMOCIONES_VER(19),
    PARAMETROS_ADMINISTRADOR(20),
    PARAMETROS_VER(21),
    CORTE_ANTICIPOS_ADMINISTRADOR(22),
    CORTE_ANTICIPOS_VER(23),
    COLABORADOR_VER(24),
    COLABORADOR_CARGA(25),
    COLABORADOR_ADMINISTRADOR(26),
    NOM035_VER(27),
    NOM035_ADMINISTRADOR(28);



    private int id;

    private PermitionENUM(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }


}
